<?php

$title = 'Send Email Announcement for Red Cedar Zen Community';
$this->headTitle($title);

$this->headScript()->prependFile($this->basePath() . '/tinymce/tinymce.min.js');
?>

<?php $this->InlineScript()->captureStart(); ?>
tinyMCE.init({
        mode : "textareas"
});
<?php $this->InlineScript()->captureEnd(); ?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<hr>

<?php if ($this->post): ?>

    <?= print_r($this->post) ?>

<?php else: ?>

<form name="EmailForm" method="post" action="" id="EmailForm">

    <div>
        <input type="hidden" name="csrf" id="csrf" value="SOME_HASH">
    </div>

    <!-- STEP 1: SELECT RESPONDENTS AND CREATE THE MESSAGE -->
    <div id="MessagePanel">

    <!-- If members.member_id is in url params -->
    <?php if ($this->member): ?>
        
        <div id="SendToMember">
            <h2>Send to: <?= $this->escapeHtml($this->member->first_name) ?> (<?= $this->escapeHtml($this->member->email) ?>)</h2>
        </div>

    <?php else: ?>

        <div id="SendToGroup">
            <h2>Send to:</h2>

            <em>Membership:</em>
                <input type="radio" name="send_to" value="members" checked="checked" id="members"><label for="members">Members</label>
                
                <input type="radio" name="send_to" value="friends" id="friends"><label for="friends">Friends</label>

                <input type="radio" name="send_to" value="members_and_friends" id="members+friends"><label for="members+friends">Members + Friends</label>

                <input type="radio" name="send_to" value="non_members" id="non_members"><label for="non_members">Non-Members (on mailing list only)</label>

                <input type="radio" name="send_to" value="all_members" id="all_members"><label for="all_members">All (everyone: members, friends &amp; non-members)</label>
                <br>
                
            <em>Location:</em>
                <input type="radio" name="location" value="local" id="local_radio"><label for="local_radio">Local</label>

                <input type="radio" name="location" value="remote" id="remote_radio"><label for="remote_radio">Remote</label>

                <input type="radio" name="location" value="all" checked="checked" id="all_radio"><label for="all_radio">All</label>
        </div>

    <?php endif; ?>
    <!-- -->

        <br>

        <div ID="SubjectPanel">
            <h2>Subject:</h2> 
            <input name="message_subject" type="text" placeholder="From the Red Cedar Zen Community" id="subject_textbox" style="width:100%;">
        </div>

        <!-- rich text editor -->
        <textarea name="message_content"></textarea>
        
        <br>

        <div class="smalltext">
            <b>Membership Use Only:</b>
            <br>
 
            <input type="checkbox" name="member_info" id="member_info_checkbox">Sangha Directory Proofing - append each person's contact info to the message they receive.
            <br>
 
            <input type="checkbox" name="tax_receipt" id="tax_receipt_checkbox">Tax Receipt for 
            <select name="tax.year" id="tax_year_select">
                <option value="2012">2012</option>
                <option value="2013">2013</option>
            </select> - append tax receipt wording to the end of the email.)
        </div>

        <p>NOTE: To send a message to an individual person using this system, go to the <a href="<?php echo $this->url('members', array('action'=>'index'));?>">Mailing List</a> and click on the person's email address.</p>

        <div class="center">
            <input type="submit" name="action" value="send_message">
        </div>
    </div>

    <!-- STEP 2: CONFIRM -->

    <!-- STEP 3: RESULTS -->

</form>

<?php endif; ?>