<?php

$title = 'Send Email Announcement';
$this->headTitle($title);

$this->headScript()->prependFile($this->basePath() . '/js/tinymce/tinymce.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/tinymce-v4.editor.js');
?>

<?php if ($this->post): ?>

    <?= print_r($this->post) ?>

<?php else: ?>

<?php $this->headStyle()->captureStart() ?>
input[type=text] {
    padding: 0.4em 0 0.3em 0.4em;
    width: 90%;
}
.message-label {
    font-size:1.2em; 
    font-weight:normal;
    font-family: Baskerville,Georgia,'Times New Roman',Times,serif;
    vertical-align: 3px;
}
select.tax-year { width: 5em; }
select.members-group {
    font-size: x-large;
    height: 120%;
    width: 300px;
    1padding: 0.1em;
}
h2.inline {
    display: inline;
    vertical-align: -1px;
}
.radio-row label {
    display: inline;
    margin-left: 5px;
}
<?php $this->headStyle()->captureEnd();
?>

<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('mail', array('action' => 'review')));
$form->prepare();

echo $this->form()->openTag($form) . "\n";
echo "\t" . $this->formRow($form->get('security')) . '<br>';
?>

    <div id="MessagePanel">
        <?php if ($form->get('id')): ?>
        <?= $this->formHidden($form->get('id')) ?>
        <?php endif; ?>

    <?php if ($this->member): ?>
        <div id="SendToMember">
            <h2>Send to: <?= $this->escapeHtml($this->member->first_name) ?> (<?= $this->escapeHtml($this->member->email) ?>)</h2>
            <?php /*<input type="hidden" name="send_to" value="<?= $this->member->id ?>">*/ ?>
        </div>


    <?php else: ?>

        <div id="SendToGroup">
            <h2 class="inline">Send to: </h2><?= $this->formRow($form->get('send_to')) ?>
            <br><br>
                
            <div class="radio-row">
                <em>Select Locale:</em> <?= $this->formRow($form->get('location')) ?>
            </div>
        </div>

    <?php endif; ?>
    <!-- -->

        <hr>

        <div ID="Message">
            <div class="subject">
                <span class="message-label">Subject: </span> <?= $this->formRow($form->get('message_subject')) ?>
            </div>
            <br>

            <span class="message-label">Message: </span> <br>
            <?= $this->formRow($form->get('message_content')) ?>
            
            <br>

            <div class="smalltext">
                <b>Membership Use Only:</b>
                <br>
                
                <?= $this->formRow($form->get('member_info')) ?> Sangha Directory Proofing - append each person's contact info to the message they receive.
                <br>
     
                <?= $this->formRow($form->get('tax_receipt')) ?> Tax Receipt for 
                <?= $this->formRow($form->get('tax_year')) ?> - append tax receipt wording to the end of the email.
            </div>
        </div>

        <p>NOTE: To send a message to an individual person using this system, go to the <a href="<?php echo $this->url('members', array('action'=>'index'));?>">Mailing List</a> and click on the person's email address.</p>

        <div style="float:right;">
            <?= $this->formRow($form->get('submit')) ?>
        </div>
    </div>

<?= $this->form()->closeTag(); ?>

<?php endif; ?>