<?php

$title = 'Send Email Announcement for Red Cedar Zen Community';
$this->headTitle($title);

//$this->headScript()->prependFile($this->basePath() . 'somefile.js');

//var_dump($this->message);

?>

<form name="ReviewForm" method="post" action="">

    <h1 align="center"><?= $title ?></h1>

    <div id="ResultsMessageLabel">
        <p>Message will be sent to: <em><?php if ($this->member): ?>
            <?= $this->member->getFullName() ?> (<?= $this->member->email ?>)
        <?php else: ?>
            <?= $this->to ?>
        <?php endif; ?></em>
        <br>
        and cc sent to mailings@sanghasoftware.com</p>

        <p><em><b>Subject</b></em>: <!-- message.subject --><?= $this->message['message_subject'] ?><!-- message.subject --></p>

        <hr>
    </div>
    
    <p><em><b>Message as text/html</b></em>:</p>

    <section id="html_message">
        <!-- email.message start -->
        <?= $this->message['message_content'] ?>
        <br>
        <!-- email.message end -->

        <?php if (isset($this->option['proofing']) && $this->member): ?>
        <!-- member.info start -->
        <table border='0' width=100%>
            <tr>
                <td>
                    <b><?= $this->member->getFullName() ?></b> <br>
                    <span class="smalltext">
                        Volunteering: <?= $this->member->sangha_jobs ?> <br>
                        Interested in: <?= $this->member->volunteer_interests ?>
                    </span>
                </td>
                <td>
                    <span class="smalltext">
                        <i>home:</i> <?= $this->member->home_phone ?> <br>
                        <?= $this->member->email ?>
                    </span>
                </td>
                <td>
                    <span class="smalltext">
                        <?= $this->member->getAddress(true) ?>
                    </span>
                </td>
                <td>
                    <span class="smalltext">
                        <?= $this->member->getMemberType() ?>
                    </span>
                </td>
            </tr>
        </table>
        <!-- member.info end -->
        <?php endif; ?>

        <?php if (isset($this->option['tax_receipt'])): ?>
        <!-- tax.receipt start -->
        <hr>
        <div>
            This message is from the Red Cedar Zen Community. <br>
            For tax purposes, please retain this letter in your records as receipt for this contribution during the <?= $this->option['tax_year'] ?> tax year. Your donation to the Red Cedar Zen Community, a publicly supported 501 (c) (3) non-profit corporation (EIN#26-0387536), is entirely tax deductible. No goods or services were received in exchange for this gift.
        <div>
        <!-- tax.receipt end -->
        <?php endif; ?>

        <hr>
        <div style="font-size:x-small;">
            This message is from the Red Cedar Zen Community. <br>
            More information is available at <a href='http://www.redcedarzen.org/'>www.redcedarzen.org</a> <br>

            For membership information or mailing list questions write to <a href='mailto:info@redcedarzen.org'>info@redcedarzen.org</a> <br>

            To register for a retreat write to <a href='mailto:registrar@redcedarzen.org'>registrar@redcedarzen.org</a> <br>

            To reach resident priest Nomon Tim Burnett write to <a href='mailto:tim@redcedarzen.org'>tim@redcedarzen.org</a>
        </div>
    </section>
        
    <hr>

    <p><em><b>Message as text/plain</b></em>:</p>

    <section>
        <pre id="text_message">
<?= strip_tags($this->message['message_content']) ?>

<?php if (isset($this->option['proofing']) && $this->member): ?>

<?= $this->member->getFullName() ?> - <?= $this->member->getMemberType() ?>

<?= $this->member->getAddress() ?>

home: <?= $this->member->home_phone ?>

<?= $this->member->email ?>

Volunteering: <?= $this->member->sangha_jobs ?>

Interested in: <?= $this->member->volunteer_interests ?>

<?php endif; ?>

This message is from the Red Cedar Zen Community.
<?php if (isset($this->option['tax_receipt'])): ?>

For tax purposes, please retain this letter in your records as receipt for this contribution during the <?= $this->option['tax_year'] ?> tax year. Your donation to the Red Cedar Zen Community, a publicly supported 501 (c) (3) non-profit corporation (EIN#26-0387536), is entirely tax deductible. No goods or services were received in exchange for this gift.
<?php endif; ?>

More information is available at <a href='http://www.redcedarzen.org/'>www.redcedarzen.org</a>
For membership information or mailing list questions write to <a href='mailto:info@redcedarzen.org'>info@redcedarzen.org</a>
To register for a retreat write to <a href='mailto:registrar@redcedarzen.org'>registrar@redcedarzen.org</a>
To reach resident priest Nomon Tim Burnett write to <a href='mailto:tim@redcedarzen.org'>tim@redcedarzen.org</a>
        </pre>
    </section>

    <span>[This message will be sent to <?= $this->to ?>]</span>

    <input type="submit" name="action" value="Send">

</form>
