<?php

$title = 'Email Announcement has been sent';
$list = $this->recipient;

if (isset($this->members_list) && is_array($this->members_list)) {

    $members = array();
    $list = '';
    foreach ($this->members_list as $member) {
        $list .= sprintf("%s &lt;%s&gt;\n", $member->getFullName(), $member->email);
        array_push($members, $member);
    }
}
?>
<html>
<head>
    <?= $this->headTitle($title) ?>
    <style>
    h2 {
        margin: 1em;
    }
    </style>
</head>
<body>
    
    <div style="margin: 25px 50px 0;">
    <?php if ($this->review): ?>

        <form action="" method="post" style="float:right;">
            <input type="submit" name="action" value="Edit" style="padding: 0.25em 0.5em;">
            <input type="submit" name="action" value="Send" style="padding: 0.25em 0.5em;">
        </form>
        <h2>The following message will be sent to: <a title="<?= $list ?>"><?= $this->recipient ?></a></h2>

    <?php else: ?>

        <form action="" method="post" style="float:right;">
            <button type="submit" formaction="/members" style="padding: 0.25em 0.5em;">&laquo; Return</button>
        </form>
        <h2>The following message has been sent to: <a title="<?= $list ?>"><?= $this->recipient ?></a></h2>

    <?php endif; ?>
    </div>
    
    <div id="The message">

        <?= $this->content ?>

    </div>
    
</body>
</html>