                <ul class="xoxo">

                    <li id="search-5" class="widget-container widget_search">
                        <form role="search" method="get" id="searchform" action="http://www.redcedarzen.org/" >
                            <div>
                                <label class="screen-reader-text" for="s">Search for:</label>
                                <input type="text" value="" name="s" id="s" />
                                <input type="submit" id="searchsubmit" value="Search" />
                            </div>
                        </form>
                    </li>
                    <li id="events-widget-3" class="widget-container events">
                        <h3 class="widget-title">Upcoming Events</h3>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=146">SPRING STUDY SERIES: THE ZEN PRECEPTS - Wednesday March 27, 2013</a>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=99">Samish Island Sesshin 2013 - Friday June 14, 2013</a>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=135">Opening the Mountains Hike - Saturday July 13, 2013</a>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=137">Meditation in the Old Growth - Saturday August 3, 2013</a>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=147">Half-Day Retreat and Priest Ordination - Sunday August 11, 2013</a>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=139">Mountains and Rivers Hiking Retreat with Bob Penny, M.S., and Nomon Tim Burnett - Wednesday August 14, 2013</a>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=142">Nature Awareness Workshop - Thursday August 15, 2013</a>
                        <p><a href="http://www.redcedarzen.org/index.php/events/?ee=140">Circumambulation of the Three Sisters (Oregon) - Thursday September 12, 2013</a>
                    </li>
                    <li id="categoryposts-3" class="widget-container widget_categoryposts">
                        <h3 class="widget-title"><a href="http://www.redcedarzen.org/index.php/category/talks/">Latest Talks</a></h3>
                        
                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/04/the-practice-of-generosity-not-killing-not-stealing/" rel="bookmark" title="Permanent link to The Practice of Generosity: Not Killing &amp; Not Stealing">The Practice of Generosity: Not Killing &#038; Not Stealing</a>
                            
                            <div class="post-date">Heigaku Talus Latona</div>
                            <div class="post-date">12 Apr 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/04/an-introduction-to-the-precepts/" rel="bookmark" title="Permanent link to An Introduction to the Precepts">An Introduction to the Precepts</a>
                                
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">3 Apr 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/03/seven-factors-of-awakening-talk-8-equanimity/" rel="bookmark" title="Permanent link to Seven Factors of Awakening &#8211; talk 8 &#8211; Equanimity">Seven Factors of Awakening &#8211; talk 8 &#8211; Equanimity</a>
                                
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">28 Mar 2013</div>
                            <br/>
                        </div>
                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/03/seven-factors-of-awakening-talk-7-concentration/" rel="bookmark" title="Permanent link to Seven Factors of Awakening &#8211; talk 7 &#8211; Concentration">Seven Factors of Awakening &#8211; talk 7 &#8211; Concentration</a>
                                
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">13 Mar 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/03/seven-factors-of-awakening-talk-6-calm/" rel="bookmark" title="Permanent link to Seven Factors of Awakening – talk 6 – Calm">Seven Factors of Awakening – talk 6 – Calm</a>
                                
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">2 Mar 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/03/living-in-vow-talk-2/" rel="bookmark" title="Permanent link to Living in Vow &#8211; talk 2">Living in Vow &#8211; talk 2</a>
                            
                            <div class="post-date">Zoketsu Norman Fischer</div>
                            <div class="post-date">2 Mar 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/03/courage-and-blind-spots-2/" rel="bookmark" title="Permanent link to Courage and Blind Spots">Courage and Blind Spots</a>
                            
                            <div class="post-date">Heigaku Talus Latona</div>
                            <div class="post-date">1 Mar 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/03/living-in-vow-talk-1/" rel="bookmark" title="Permanent link to Living in Vow &#8211; talk 1">Living in Vow &#8211; talk 1</a>
                            
                            <div class="post-date">Zoketsu Norman Fischer</div>
                            <div class="post-date">1 Mar 2013</div>
                            <br/>
                        </div>
                    </li>
                    <li id="categoryposts-2" class="widget-container widget_categoryposts">
                        <h3 class="widget-title"><a href="http://www.redcedarzen.org/index.php/category/related-events/">Related Events</a></h3>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/02/freedom-in-a-female-form-feb-7-9/" rel="bookmark" title="Permanent link to Freedom in a Female Form &#8211; March 8-10">Freedom in a Female Form &#8211; March 8-10</a>
                            
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">8 Feb 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/01/the-whole-universe-one-bright-pearl-the-teachings-of-dogen-zenji/" rel="bookmark" title="Permanent link to The Whole Universe One Bright Pearl: the teachings of Dogen Zenji (Vancouver)">The Whole Universe One Bright Pearl: the teachings of Dogen Zenji (Vancouver)</a>
                            
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">8 Jan 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2013/01/sunday-talks-at-seattle-soto-zen/" rel="bookmark" title="Permanent link to Sunday Talks at Seattle Soto Zen">Sunday Talks at Seattle Soto Zen</a>
                            
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">3 Jan 2013</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2012/12/mindful-recovery-group/" rel="bookmark" title="Permanent link to Mindful Recovery Group">Mindful Recovery Group</a>
                            
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">30 Dec 2012</div>
                            <br/>
                        </div>

                        <div class="cat-post-item">
                            <a class="post-title" href="http://www.redcedarzen.org/index.php/2012/12/mindfulness-northwest-winter-2013/" rel="bookmark" title="Permanent link to Mindfulness Northwest &#8211; Winter 2013">Mindfulness Northwest &#8211; Winter 2013</a>
                            
                            <div class="post-date">Nomon Tim Burnett</div>
                            <div class="post-date">30 Dec 2012</div>
                            <br/>
                        </div>
                    </li>
                </ul><!-- Unified into one widget area, as of 1.1.8 -->
