<?php
$this->headTitle('Red Cedar Zen Community');
$this->headTitle('An Everyday Zen Community in Bellingham, WA');
$this->headTitle()->setSeparator(' » ');
?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
    <meta charset="UTF-8" />
    <?= $this->headTitle() ?>

    <link rel='canonical' href='http://www.redcedarzen.org/' />

    <!-- <link rel="stylesheet" type="text/css" media="all" href="http://www.redcedarzen.org/wp-content/themes/brunelleschi.1.4.2/brunelleschi/style.css" /> -->
    <link rel="stylesheet" type="text/css" media="all" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" media="all" href="/css/brunelleschi.css" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
        #wrapper { max-width: 1140px !important; }
        1#branding {  display: none; } /* hide theme branding */
        #main h1, #main h2, #main h3,
        #main h4, #main h5, #main h6 { 
            margin: 0px; 10px; 10px; 0px;  
            line-height: 1.2em;
        } /* not so much vertical space after headers */
        .entry-content .error label {color: red;}
        .error input {background: red;}
        blockquote {font-style: normal;}        
    </style>
    <?php echo $this->headStyle() ?>
    
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-content/themes/brunelleschi.1.4.2/brunelleschi/js/modernizr-2.0.6.min.js?ver=2.0.6'></script>
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-content/themes/brunelleschi.1.4.2/brunelleschi/js/respond.js?ver=3.5.1'></script>
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-includes/js/jquery/jquery.js?ver=1.8.3'></script>
    <script type="text/javascript" src="http://www.redcedarzen.org/custom/scripts/zen.js"></script>
    <?php echo $this->headScript() ?>
</head>
<body class="home page page-id-83 page-template page-template-page_notitle-php">
    <div id="wrapper" class="hfeed container">

        <header id="header" class="row clearfix">

            <!-- Test if the User is connected -->
            <?php if(!$this->zfcUserIdentity()): ?>
                <!-- display the login form -->
                <?php //echo $this->zfcUserLoginWidget(array('redirect'=>'user')); ?>
            <?php else: ?>
                <span style="float:right;">
                    <a href="/user" class="user-login">
                        <?php echo $this->zfcUserIdentity()->getDisplayname() ?>
                    </a>
                    | <a href="/user/logout">logout</a>
                </span>
            <?php endif?>

            <div id="banner">
                <a href="/"><img src="http://www.redcedarzen.org/images/Banner2.jpg" width="629" height="116" alt="Red Cedar Zen Community, 1021 N Forest, Bellingham WA"/></a>
            </div>

            <?php if ($this->nav): ?>
            <div id="access" role="navigation" class="twelvecol last clearfix">
                <div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>


                <?php echo $this->nav; ?>


            </div><!-- #access -->
            <?php endif; ?>

        </header><!-- #header -->

        <div id="container" class="row">

            <div id="main" role="main" class="twelvecol ">


                <article id="content">

                <?php if(!$this->zfcUserIdentity()): ?>

                    <?php // display the login form ?>
                    <?php echo $this->zfcUserLoginWidget(); ?>

                <?php else: ?>
                    
                    <?php echo $this->content; ?>

                <?php endif?>      
                    
                </article>

            </div><!-- #main -->

        </div><!-- #container -->

        <footer id="footer" role="contentinfo" class="row">
            <div id="footerbar" class="twelvecol last"></div><!-- #footerbar -->
            <div id="colophon" class="twelvecol last">
                <div id="site-info" class="sixcol">
                    <a href="http://www.redcedarzen.org/" title="Red Cedar Zen Community" rel="home">Red Cedar Zen Community</a>
                </div><!-- #site-info -->
                <div class="sixcol last">
                    <a href="http://framework.zend.com/" style="float:right;color:#161616;text-decoration:none;" target="_blank">Built on <img src="<?= $this->serverUrl() ?>/img/zf2-logo.png" width="20"></a>
                </div>
            </div><!-- #colophon -->
        </footer><!-- #footer -->
    </div><!-- #wrapper -->
    
    <?php echo $this->inlineScript() ?>
</body>
</html>
