
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
    <meta charset="UTF-8" />
    <title>Red Cedar Zen Community &raquo; An Everyday Zen Community in Bellingham, WA</title>
    
    <script type="text/javascript" src="http://www.redcedarzen.org/custom/scripts/zen.js"></script>
    
    <link rel="profile" href="http://gmpg.org/xfn/11" />
    <link rel="stylesheet" type="text/css" media="all" href="http://www.redcedarzen.org/wp-content/themes/brunelleschi.1.4.2/brunelleschi/style.css" />
    <link rel="pingback" href="http://www.redcedarzen.org/xmlrpc.php" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
        #wrapper { max-width: 1140px !important; }
        #branding {  display: none; } /* hide theme branding */
        #main h1, #main h2, #main h3,
        #main h4, #main h5, #main h6 { 
            margin: 0px; 10px; 10px; 0px;  
            line-height: 1.2em;
        } /* not so much vertical space after headers */
        .entry-content .error label {color: red;}
        .error input {background: red;}
        blockquote {font-style: normal;}        
    </style>
    <link rel="alternate" type="application/rss+xml" title="Red Cedar Zen Community &raquo; Feed" href="http://www.redcedarzen.org/index.php/feed/" />
    <link rel="alternate" type="application/rss+xml" title="Red Cedar Zen Community &raquo; Comments Feed" href="http://www.redcedarzen.org/index.php/comments/feed/" />
    <link rel='stylesheet' id='calendar-css'  href='http://www.redcedarzen.org/wp-content/plugins/espresso-calendar.1.11/calendar.css?ver=3.5.1' type='text/css' media='all' />
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-content/themes/brunelleschi.1.4.2/brunelleschi/js/modernizr-2.0.6.min.js?ver=2.0.6'></script>
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-content/themes/brunelleschi.1.4.2/brunelleschi/js/respond.js?ver=3.5.1'></script>
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-includes/js/jquery/jquery.js?ver=1.8.3'></script>
    <script type='text/javascript'>
    /* <![CDATA[ */
    var EEGlobals = {"ajaxurl":"http:\/\/www.redcedarzen.org\/wp-admin\/admin-ajax.php","plugin_url":"http:\/\/www.redcedarzen.org\/wp-content\/plugins\/event-espresso.3.1.15.P\/","event_page_id":"586"};
    /* ]]> */
    </script>
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-content/plugins/event-espresso.3.1.15.P/scripts/espresso_cart_functions.js?ver=3.5.1'></script>
    <script type='text/javascript' src='http://www.redcedarzen.org/wp-includes/js/comment-reply.min.js?ver=3.5.1'></script>
    <link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.redcedarzen.org/xmlrpc.php?rsd" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.redcedarzen.org/wp-includes/wlwmanifest.xml" /> 
    <link rel='next' title='Weekly Schedule' href='http://www.redcedarzen.org/index.php/practice/practice-weekly-schedule/' />
    <meta name="generator" content="WordPress 3.5.1" />
    <link rel='canonical' href='http://www.redcedarzen.org/' />
    <meta name='generator' content='Event Espresso Version 3.1.15.P' /><script type="text/javascript" src="http://www.redcedarzen.org/wp-content/plugins/powerpress/player.js"></script>
    <script type="text/javascript"><!--
    function powerpress_pinw(pinw){window.open('http://www.redcedarzen.org/?powerpress_pinw='+pinw, 'PowerPressPlayer','toolbar=0,status=0,resizable=1,width=460,height=320');  return false;}
    powerpress_url = 'http://www.redcedarzen.org/wp-content/plugins/powerpress/';
    //-->
    </script>
    <?php echo $this->headScript() ?>
</head>
<body class="home page page-id-83 page-template page-template-page_notitle-php">
    <div id="wrapper" class="hfeed container">

        <header id="header" class="row clearfix">

            <div id="banner">
                <img src="http://www.redcedarzen.org/images/Banner2.jpg" width="629" height="116" alt="Red Cedar Zen Community, 1021 N Forest, Bellingham WA"/>
            </div>

            <!-- Test if the User is connected -->
            <?php if(!$this->zfcUserIdentity()): ?>
                <!-- display the login form -->
                <?php //echo $this->zfcUserLoginWidget(array('redirect'=>'user')); ?>
            <?php else: ?>
                <a href="/user" class="user-login">
                    <?php echo $this->zfcUserIdentity()->getDisplayname() ?>
                </a>
                | <a href="/user/logout">logout</a>
            <?php endif?>

            <div id="access" role="navigation" class="twelvecol last clearfix">
                <div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>


                <?php echo $this->nav; ?>


            </div><!-- #access -->

        </header><!-- #header -->

        <div id="container" class="row">

            <div id="main" role="main" class="ninecol ">


                <article id="content">

                <?php if(!$this->zfcUserIdentity()): ?>

                    <?php // display the login form ?>
                    <?php echo $this->zfcUserLoginWidget(); ?>

                <?php else: ?>
                    
                    <?php echo $this->content; ?>

                <?php endif?>
                    
                    
                </article>

            </div><!-- #main -->


            <div id="sidebar" class="widget-area threecol last " role="complementary">


                <?php //echo $this->sidebar; ?>

 
            </div><!-- #primary .widget-area -->

        </div><!-- #container -->

        <footer id="footer" role="contentinfo" class="row">
            <div id="footerbar" class="twelvecol last"></div><!-- #footerbar -->
            <div id="colophon" class="twelvecol last">
                <div id="site-info" class="sixcol">
                    <a href="http://www.redcedarzen.org/" title="Red Cedar Zen Community" rel="home">Red Cedar Zen Community</a>
                </div><!-- #site-info -->
                <div id="site-generator" class="sixcol last">
                    <a href="http://http://framework.zend.com/" title="">Built with Zend Framework.</a>
                </div><!-- #site-generator -->
            </div><!-- #colophon -->
        </footer><!-- #footer -->
    </div><!-- #wrapper -->
    
    <?php echo $this->inlineScript() ?>
</body>
</html>
