                <div class="menu-header">
                    <ul id="menu-red-cedar-menu" class="menu">
                        <li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor">
                            <a href="/">Members</a>
                            <ul class="sub-menu">
                                <li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item current_page_item"><a href="<?php $this->basePath() ?>/members/add">Add member</a></li>
                            </ul>
                        </li>

                        <li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php $this->basePath() ?>/mail">Mail Manager</a>
                            <ul class="sub-menu">
                                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-842">
                                    <a href="<?php $this->basePath() ?>/mail/new">New Message</a>
                                </li>
                                <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                    <a href="#">Email Templates</a>
                                </li>
                            </ul>
                        </li>

                        <li class="menu-item menu-item-type-post_type menu-item-object-page">
                            <a href="http://www.redcedarzen.org/index.php/category/news/">Newsletter</a>
                            <ul class="sub-menu">
                                <li class="menu-item menu-item-type-taxonomy menu-item-object-category">
                                    <a href="#">Editor</a>
                                </li>
                            </ul>
                        </li>

                        <li class="menu-item menu-item-type-post_type menu-item-object-page">
                            <a href="#">Admin</a>
                            <ul class="sub-menu">
                                <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                    <a href="#">About Zen</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>