<?php

$title = 'Edit member';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'members',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name')) . '<br>';
echo $this->formRow($form->get('email')) . '<br>';
echo $this->formRow($form->get('phone')) . '<br>';
echo $this->formRow($form->get('street')) . '<br>';
echo $this->formRow($form->get('city')) . '<br>';
echo $this->formRow($form->get('state')) . '<br>';
echo $this->formRow($form->get('zipcode')) . '<br>';
echo $this->formRow($form->get('country')) . '<br>';
echo $this->formRow($form->get('comments')) . '<br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();