<?php

$title = "Edit " . $this->name;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'members',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);


echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('security')) . '<br>';
?>

<table border=1>
    <tr>
        <td align="right">First Name </td>
        <td>
            <?= $this->formRow($form->get('first_name')) ?>
        </td>
        <td align=right>Last Name </td>
        <td>
            <?= $this->formRow($form->get('last_name')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">Home Phone </td>
        <td>
            <?= $this->formRow($form->get('home_phone')) ?>
        </td>
        <td align="right">Work Phone </td>
        <td>
            <?= $this->formRow($form->get('work_phone')) ?>
        </td>
    </tr>
    <tr>
        <td align=right>Email </td>
        <td colSpan=3>
            <?= $this->formRow($form->get('email')) ?>
        </td>
    </tr>
    <tr>
        <td align="right" style="HEIGHT: 28px">Membership
            <?= $this->formRow($form->get('membership_type')) ?>
        </td>
        <td style="HEIGHT: 28px">
            Include in Sangha Directory? <br>
            <?= $this->formRow($form->get('list_in_directory')) ?>
        </td>
        <td align=right style="HEIGHT: 28px">
            Membership last renewed
        </td>
        <td style="HEIGHT: 28px">
            <?= $this->formRow($form->get('last_renewal')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">Local Person?
            <br>
            <small>Bellingham, Seattle, Vancouver</small>
        </td>
        <td>
            <?= $this->formRow($form->get('is_local')) ?>
        </td>
        <td align="right">
            Membership Notes
        </td>
        <td>
            <?= $this->formRow($form->get('membership_notes')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">Address </td>
        <td colSpan=3>
            <?= $this->formRow($form->get('street')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">City </td>
        <td>
            <?= $this->formRow($form->get('city')) ?>
        </td>
        <td align="right">State / Province </td>
        <td>
            <?= $this->formRow($form->get('state')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">Zip / Post Code </td>
        <td>
            <?= $this->formRow($form->get('zipcode')) ?>
        </td>
        <td align="right">Country 
            <small>(blank for USA)</small>
        </td>
        <td>
            <?= $this->formRow($form->get('country')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">Current Sangha Job(s) </td>
        <td colSpan=3>
            <?= $this->formRow($form->get('current_role')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">Volunteer Interests </td>
        <td colSpan=3>
            <?= $this->formRow($form->get('volunteer_interest')) ?>
        </td>
    </tr>
    <tr>
        <td align="right">General Notes
            <br>
            <small></small>
        </td>
        <td colSpan=3>
            <?= $this->formRow($form->get('member_notes')) ?>
        </td>
    </tr>
    <tr>
        <td align="right" colSpan=2>

            <?= $this->formRow($form->get('submit')) ?>

        </td>
        <td align="left" colSpan=2>

            <button type="submit" formaction="<?php echo $this->url('members',
            array('action'=>'index'));?>">Return to list</button>

            <button type="submit" formaction="<?php echo $this->url('members',
            array('action'=>'delete', 'id' => $this->id));?>">Delete</button>

        </td>
    </tr>
</table>

<?php
echo $this->form()->closeTag();