<?php
// module/member/view/album/album/index.phtml:

$title = 'Sangha members';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('members', array('action'=>'add'));?>">Add new member</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone #</th>
    <th>Street Addr.</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Country</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($members as $member) : ?>
<tr>
    <td><?php echo $this->escapeHtml($member->first_name); ?> <?php echo $this->escapeHtml($member->last_name); ?></td>
    <td>
        <a href="<?php echo $this->url('mail', array('action'=>'new', 'id'=>$member->id));?>"><?php echo $this->escapeHtml($member->email);?></a>
    </td>
    <td>
        <?php echo $this->escapeHtml($member->home_phone);?>
    </td>
    <td><?php echo $this->escapeHtml($member->street);?></td>
    <td><?php echo $this->escapeHtml($member->city);?></td>
    <td><?php echo $this->escapeHtml($member->state);?></td>
    <td><?php echo $this->escapeHtml($member->zipcode);?></td>
    <td><?php echo $this->escapeHtml($member->country);?></td>
    <td>
        <a href="<?php echo $this->url('members',
            array('action'=>'edit', 'id' => $member->id));?>">Edit</a>
        <a href="<?php echo $this->url('members',
            array('action'=>'delete', 'id' => $member->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>