    <section>
        <h2 align="center">Prepare Sangha Directory (phone list) for Red Cedar Zen Community</h2>

        <form method="post" action="/member/phonelist" name="sangha.directory" id="sangha_directory">
            <p>Prepare Directory for:
                <br>    
                <input id="SanghaListRadio" type="radio" name="list.type" value="sangha_list" checked="checked" /><label for="SanghaListRadio">SANGHA DIRECTORY - Members who have opted in for this.</label>

                <br> 
                <input id="AllMembersRadio" type="radio" name="list.type" value="all_members" /><label for="AllMembersRadio">MEMBERSHIP LIST - All Members and Friends (for Board use)</label>

                <br>
                <input id="FullListRadio" type="radio" name="list.type" value="full_list" /><label for="FullListRadio">FULL LIST - Entire mailing list (for Board use)</label>
            </p>
            <p>
                <input type="submit" name="submit.phonelist" value="Get Phone List">
            </p>
        </form>
        
        <?php if ($_POST['submit']) ?>
        <!-- Toogle after form submission -->
        <div id="ResultsLabel">
            <p>Opening new browser window containing the printable phone list for: <br>
            Sangha Directory - Members and Friends of the Sangha who have opted in <br>
            <b>37</b> People<p>

            <p>(NOTE: Popup blockers can prevent this window from opening)</p>
        </div><!-- #ResultsLabel -->
        <?php endif; ?>

    </section>