    <h1>Mailing List &amp; Membership Tool</h1>

    <p>As of 12/30/2011 this site is only for the Red Cedar Zen Mailing List.<br>
       All website updates are via the WordPress administration available here:
       <a href="http://www.redcedarzen.org/wp-admin">www.redcedarzen.org/wp-admin</a><br>
       Ask Terry Thompson, Jay Allen, or Tim Burnett for an account to access WordPress.</p>


    <div id="col1">
        <h2>Mailing List</h2> 
         <ul>
            <li><a href="<?= $this->basePath() ?>/members">View &amp; Edit Mailing List</a></li>
            <li><a href="<?= $this->basePath() ?>/mail">Send Email Announcement</a></li>
            <li><a href="<?= $this->basePath() ?>/labels">Mailing Labels</a></li>
            <li><a href="<?= $this->basePath() ?>/directory">Sangha Directory</a></li>
        </ul>

        <h2>For Reference</h2>
        <ul>
            <li><a href="../events_archive.html">Event Descriptions Archive</a></li>
            <li><a href="http://docs.google.com" target="_blank">Google Docs</a> login as user: <i>redcedarinfo</i>  pwd: <i>zoketsuzen</i></li>
            <li><a href="http://picasaweb.google.com/redcedarinfo" target="_blank">Picasa Photos</a> Storage for our photos. <br>To make changes, login as user: <i>redcedarinfo</i>  pwd: <i>zoketsuzen</i></li>
        </ul>
    </div>