<?php

$title = 'Delete member';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($member->getFullName()); ?>' by
    '<?php echo $this->escapeHtml($member->email); ?>'?
</p>
<?php
$url = $this->url('members/delete', array('id' => $this->id));
?>
<form action="<?= $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?= (int) $member->id; ?>" />
    <input class="btn" type="submit" name="del" value="Yes" />
    <input class="btn" type="submit" name="del" value="No" />
</div>
</form>