    <section id="PhoneListLabel">
        
        <!-- <div>Red Cedar Zen Community - Sangha Directory - printed 4/18/2013</div> -->
        <div align='center'>Red Cedar Zen Community - Membership List (Board use only) - printed 4/18/2013</div>
        <!-- <div>Red Cedar Zen Community - Full Mailing List (Board use only) - printed 4/18/2013</div> -->


        <div>&nbsp;</div>

        <table border=0 width=100%>
            <tr>
                <td><b>Name</b></td>
                <td><b>Phone &amp; Email</b></td>
                <td><b>Address</b></td>
                <td><b>Membership</b></td>
            </tr>

            <?php foreach ($this->member): ?>
            <tr style='page-break-inside : avoid;'>
                <td>
                    <b><?= $this->member->name ?></b> <br>
                    <?php if ($this->member->interested_in): ?>
                    Interested in: <?= $this->member->interested_in ?>
                    <?php endif; ?>
                </td>
                <td class="smalltext">
                    <?php if ($this->member->home_phone): ?>
                    Home: <?= $this->member->home_phone ?>
                    <?php endif; ?>
                    <?php if ($this->member->work_phone): ?>
                    Work: <?= $this->member->work_phone ?>
                    <?php endif; ?>
                    <?= $this->member->email ?>
                </td>
                <td class="smalltext">
                    <?php if ($this->member->street): ?>
                    <?= $this->member->street ?> <br>
                    <?= $this->member->city . ', ' . $this->member->state . ' ' . $this->member->zipcode ?> <br>
                    <?= $this->member->country ?>
                    <?php endif; ?>
                </td>
                <td class="smalltext">
                    <?= $this->member->membership_type // Friend or Member ?>
                </td>
            </tr>
            <tr>
                <td colspan=4 style='height:2px;'><HR></td>
            </tr>

            <?php endforeach; ?>
        </table>
    </section>
