<?php
$title = 'Roles of Sangha Members';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
.picker-bar > form {
    width: 100%;
}
.picker > input {
    1color: Black;
    1background-color: LightCyan;
    border: solid 1px gray;
    width: 30px;
}
.picker > input.selected {
     color: White;
     background-color: Gray;
}
<?php $this->headStyle()->captureEnd();
?>
<h1><?php echo $this->escapeHtml($title); ?> (<?= count($members) ?> total)</h1>
<hr>


<table class="table">

<?php foreach ($members as $member) : ?>
<tr id="<?php echo $this->escapeHtml($member->id) ?>">
    <td><?php echo $this->escapeHtml($member->getFullName()) ?></td>
    <td>
        <a href="<?php echo $this->url('mail/member', array('id'=>$member->id));?>"><?php echo $this->escapeHtml($member->email);?></a> <br>
        <?php echo $this->escapeHtml($member->home_phone);?>
    </td>
    <?php /* <td><?php echo $this->escapeHtml($member->getAddress());?></td> */ ?>
    <td><?php echo $this->escapeHtml($member->sangha_jobs);?></td>
    <td>
        <a href="<?php echo $this->url('members',
            array('action'=>'edit', 'id' => $member->id));?>">Edit</a>
    </td>
</tr>

<?php endforeach; ?>
</table>