<?php
$title = 'Roles of Sangha Members';
$this->headTitle($title);
?>
<?php //$this->headStyle()->captureStart() ?>

<?php //$this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?> (<?= count($members) ?> total)</h1>
<hr>


<table class="table">

<?php foreach ($members as $member) : ?>
<tr id="<?php echo $this->escapeHtml($member->id) ?>">
    <td><?php echo $this->escapeHtml($member->getFullName()) ?></td>
    <td>
        <a href="<?php echo $this->url('mail/member', array('id'=>$member->id));?>"><?php echo $this->escapeHtml($member->email);?></a> <br>
        <?php echo $this->escapeHtml($member->home_phone);?>
    </td>
    <?php /* <td><?php echo $this->escapeHtml($member->getAddress());?></td> */ ?>
    <td><?php echo $this->escapeHtml($member->sangha_jobs);?></td>
    <td>
        <a href="<?php echo $this->url('members/role-edit',
            array('id' => $member->id));?>">Edit</a>
    </td>
</tr>

<?php endforeach; ?>
</table>