<?php

$title = 'Members group: ';
$this->headTitle($title);

if ( ! $this->members) {
    die('No members');
}
?>
<h1><?php echo $this->escapeHtml($title) . ' ' . $this->group_list ?></h1>
<h2><?php echo count($this->members) ?> members currently.</h2>

<?php //var_dump($this->members) ?>

<?php
foreach ($this->members as $member) {
    echo sprintf("%s &lt;%s&gt;, %s<br>",
        $this->escapeHtml($member->getFullName()),
        $this->escapeHtml($member->email),
        $this->escapeHtml($member->getMemberType())
    );
}